services:

  postgres:
    image: "postgres:17.2"
    ports:
      - "6675:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    restart: always
  node:
    build: .
    restart: always
    ports: 
      - "5000:5000"
    volumes:
      - ~/smm-data:/app/data/avatars:rw

